name: cafeemployeeapp

services:
  ui:
    container_name: ui
    build:
      context: ./CafeEmployeeApp
    ports:
      - 5173:80
  api:
    container_name: api
    build:
      context: ./CafeEmployeeApi
    environment:
      - ASPNETCORE_URLS=http://*:80
    ports:
      - 5191:80
    depends_on:
      - sql_server
  sql_server:
    container_name: sql_server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=sQLs3rverRpAssw0rD!!
    ports:
      - 1433:1433
    volumes:
      - /c/Apps/cafeemployeeapp/db/data:/var/opt/mssql/data
      - /c/Apps/cafeemployeeapp/db/log:/var/opt/mssql/log