@CafeEmployeeApi_HostAddress = http://localhost:5191

### CAFES
GET {{CafeEmployeeApi_HostAddress}}/cafes
Accept: application/json
If-Modified-Since: Sat, 12 Apr 2025 07:55:02 GMT
###
GET {{CafeEmployeeApi_HostAddress}}/cafes?location=
Accept: application/json
If-Modified-Since: Fri, 11 Apr 2025 05:35:50 GMT
###
GET {{CafeEmployeeApi_HostAddress}}/cafes?location=Singapore
Accept: application/json
If-Modified-Since: Fri, 11 Apr 2025 05:35:50 GMT
###
GET {{CafeEmployeeApi_HostAddress}}/cafes?location=Philippines
Accept: application/json
If-Modified-Since: Fri, 11 Apr 2025 05:53:40 GMT
###
GET {{CafeEmployeeApi_HostAddress}}/cafes?location=us
Accept: application/json
###
GET {{CafeEmployeeApi_HostAddress}}/cafes?location=invalid
Accept: application/json
If-Modified-Since: Sat, 12 Apr 2025 09:05:23 GMT

###
GET {{CafeEmployeeApi_HostAddress}}/cafes/23058923-a46e-41fe-838c-9cc823a00ac9
Accept: application/json
###

GET {{CafeEmployeeApi_HostAddress}}/cafes/xxx
Accept: application/json

### Create Cafe Requests
POST {{CafeEmployeeApi_HostAddress}}/cafe
Content-Type: application/json
Accept: application/json

{
    "name": "CafeNewDel",
    "description": "Created best cafe ever!!!",
    "location": "Japan"
}
###
POST {{CafeEmployeeApi_HostAddress}}/cafe
Content-Type: application/json
Accept: application/json

{
    "name": "My Invalid Cafeeeee",
    "description": "Created best cafe ever!!! Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!",
    "location": ""
}
###
DELETE  {{CafeEmployeeApi_HostAddress}}/cafe/23058923-a46e-41fe-838c-9cc823a00ac9
Accept: application/json
### hAS ISSUE
GET  {{CafeEmployeeApi_HostAddress}}/cafes/5C0BB65C-6311-4842-B7B6-15AF1F277043
Accept: application/json
If-Modified-Since: Sat, 12 Apr 2025 07:55:02 GMT

###
GET  {{CafeEmployeeApi_HostAddress}}/cafes/5397E134-111F-4B6B-ADE1-8FE4720711A9
Accept: application/json


###
PUT {{CafeEmployeeApi_HostAddress}}/cafe/5c0bb65c-6311-4842-b7b6-15af1f277043
Content-Type: application/json
Accept: application/json
If-Match: AAAAAAAAVgI=

{
    "name": "CafeNew2",
    "description": "Best cafe in town - 1",
    "location": "US"
}



### EMPLOYEES
GET {{CafeEmployeeApi_HostAddress}}/employees
Accept: application/json
If-Modified-Since: Fri, 11 Apr 2025 08:17:29 GMT
###
GET {{CafeEmployeeApi_HostAddress}}/employees?cafe=
Accept: application/json

###
GET {{CafeEmployeeApi_HostAddress}}/employees?cafe=F3F38874-D98B-40A5-9637-AE0883ADDE08
Accept: application/json
###
GET {{CafeEmployeeApi_HostAddress}}/employees?cafe=b13633e7-45ac-4cd9-8a28-1cd78725aec2
Accept: application/json

###
GET {{CafeEmployeeApi_HostAddress}}/employees?cafe=invalid
Accept: application/json

###
GET {{CafeEmployeeApi_HostAddress}}/employees/UImKCcFpN5i7f
Accept: application/json
###
GET {{CafeEmployeeApi_HostAddress}}/employees/UIXwUdQJncNpL
Accept: application/json
If-Modified-Since: Thu, 10 Apr 2025 16:57:45 GMT

###
GET {{CafeEmployeeApi_HostAddress}}/employees/xxx
Accept: application/json

###
POST {{CafeEmployeeApi_HostAddress}}/employee
Content-Type: application/json
Accept: application/json

{
    "name": "newemp",
    "emailAddress": "dudududu@gmail.com",
    "phoneNumber": "88123456",
    "gender": 1,
    "assignedCafeId": "5dc823f9-47c4-47aa-8654-f26956c37488"
}
###
POST {{CafeEmployeeApi_HostAddress}}/employee
Content-Type: application/json
Accept: application/json

{
    "name": "EmpDel2",
    "emailAddress": "employee1@cafe.com",
    "phoneNumber": "82345672",
    "gender": 0,
    "assignedCafeId": "2A388857-9226-4529-B005-AD8A2E34B44A"
}
###
POST {{CafeEmployeeApi_HostAddress}}/employee
Content-Type: application/json
Accept: application/json

{
    "name": "T",
    "emailAddress": "T",
    "phoneNumber": "9000000x"
}

###
DELETE {{CafeEmployeeApi_HostAddress}}/employee/UINQUfoAcZX02
Accept: application/json

###
PUT {{CafeEmployeeApi_HostAddress}}/employee/UImKCcFpN5i7f
Content-Type: application/json
Accept: application/json
If-Match: AAAAAAAAB9s=

{
    "name": "Employee5U",
    "emailAddress": "dudududu@gmail.coms",
    "phoneNumber": "88123459",
    "gender": 1
    

}

  
