@CafeEmployeeApi_HostAddress = http://localhost:5191

### CAFES
GET {{CafeEmployeeApi_HostAddress}}/cafes
Accept: application/json
###
GET {{CafeEmployeeApi_HostAddress}}/cafes?location=
Accept: application/json
###
GET {{CafeEmployeeApi_HostAddress}}/cafes?location=Philippines
Accept: application/json
###
GET {{CafeEmployeeApi_HostAddress}}/cafes?location=us
Accept: application/json
###
GET {{CafeEmployeeApi_HostAddress}}/cafes?location=invalid
Accept: application/json

###
GET {{CafeEmployeeApi_HostAddress}}/cafes/9ddea15d-a385-406f-9afc-4ba1d38458dd
Accept: application/json
###

GET {{CafeEmployeeApi_HostAddress}}/cafes/xxx
Accept: application/json

### Create Cafe Requests
POST {{CafeEmployeeApi_HostAddress}}/cafe
Content-Type: application/json
Accept: application/json

{
    "name": "CafeNew2",
    "description": "Created best cafe ever!!!",
    "location": "Singapore"
}
###
POST {{CafeEmployeeApi_HostAddress}}/cafe
Content-Type: application/json
Accept: application/json

{
    "name": "My Invalid Cafeeeee",
    "description": "Created best cafe ever!!! Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!Created best cafe ever!!!",
    "location": ""
}
###
DELETE  {{CafeEmployeeApi_HostAddress}}/cafe/b13633e7-45ac-4cd9-8a28-1cd78725aec2
Accept: application/json
###
GET  {{CafeEmployeeApi_HostAddress}}/cafes/d358840b-0053-4136-a8f8-1c30941fc21d
Accept: application/json
###
PUT {{CafeEmployeeApi_HostAddress}}/cafe/9ddea15d-a385-406f-9afc-4ba1d38458dd
Content-Type: application/json
Accept: application/json

{
    "name": "Cafe 1",
    "description": "updated desc",
    "location": "Singapore"
}



### EMPLOYEES
GET {{CafeEmployeeApi_HostAddress}}/employees
Accept: application/json
###
GET {{CafeEmployeeApi_HostAddress}}/employees?cafe=
Accept: application/json

###
GET {{CafeEmployeeApi_HostAddress}}/employees?cafe=F3F38874-D98B-40A5-9637-AE0883ADDE08
Accept: application/json
###
GET {{CafeEmployeeApi_HostAddress}}/employees?cafe=b13633e7-45ac-4cd9-8a28-1cd78725aec2
Accept: application/json

###
GET {{CafeEmployeeApi_HostAddress}}/employees?cafe=invalid
Accept: application/json

###
GET {{CafeEmployeeApi_HostAddress}}/employees/UIXwUdQJncNpL
Accept: application/json

###
GET {{CafeEmployeeApi_HostAddress}}/employees/xxx
Accept: application/json

###
POST {{CafeEmployeeApi_HostAddress}}/employee
Content-Type: application/json
Accept: application/json

{
    "name": "new start",
    "emailAddress": "dudududu@gmail.com",
    "phoneNumber": "88123456",
    "gender": 1,
    "assignedCafeId": "f3f38874-d98b-40a5-9637-ae0883adde08"
}
###
POST {{CafeEmployeeApi_HostAddress}}/employee
Content-Type: application/json
Accept: application/json

{
    "name": "EmpNew",
    "emailAddress": "employee1@cafe.com",
    "phoneNumber": "82345672",
    "gender": 0
}
###
POST {{CafeEmployeeApi_HostAddress}}/employee
Content-Type: application/json
Accept: application/json

{
    "name": "T",
    "emailAddress": "T",
    "phoneNumber": "9000000x"
}

###
DELETE {{CafeEmployeeApi_HostAddress}}/employee/UIl0pCoD49f8L
Accept: application/json

###
PUT {{CafeEmployeeApi_HostAddress}}/employee/UIXwUdQJncNpL
Content-Type: application/json
Accept: application/json

{
    "name": "darahu",
    "emailAddress": "dudududu@gmail.coms",
    "phoneNumber": "88123459",
    "gender": 1,
    "assignedCafeId": "DE15717D-F7AF-466E-886E-F485C0A712F9"
    

}

  
